### ISSUE TITLE
Support for 9.x GHC compiler

### ISSUE THREAD

**Issue by TheCharmingSociopath** [meamy/feynman#10]
The library does not build with GHC 9.x. I tried to build with `GHC 9.8.2`, and the compiler throws multiple errors, generally saying things similar to: it is unable to find the function `foldM` on line 143 of `Synthesis/Reversible.hs` (with similar errors in the file `Reversible`).

This is fixed by importing `Control.Monad` in the files.

It seems to be working with the earlier versions of GHC because it is imported in `Feynman.Core`, which in turn is imported in `Symbolic` and `Reversible`, and GHC might have changed its nested visibility rules between these versions.

**Comment by meamy** [comment]
Thanks for the bug report! Can you confirm that it's fixed in the latest commit on the master branch?

**Comment by TheCharmingSociopath** [comment]
Nope, [this PR](https://github.com/meamy/feynman/pull/11) works. 
Newbie to Haskell, please check.

**Comment by meamy** [comment]
Thanks, closing!
