### ISSUE TITLE
Some questions about .qc format

### ISSUE THREAD

**Issue by alan23273850** [meamy/feynman#5]
1. In https://github.com/meamy/feynman/blob/master/src/Feynman/Verification/Symbolic.hs, Toffoli gates are not supported. Is there any workaround to support it?

2. In https://github.com/meamy/feynman/blob/master/benchmarks/grover_5.qc, why do Z gates and Zd gates have three inputs and outputs?

To sum up, do we have a formal spec about .qc circuit, and does it meet the spec of https://github.com/meamy/feynman/blob/master/src/Feynman/Verification/Symbolic.hs?
Thanks!

**Comment by meamy** [comment]
1. Toffoli gates are supported in a few ways, depending on your use case. For historical reasons, Toffoli gates which are written as `tof x y z` in .qc are translated to Clifford + T internally in Feynman, so if you want to verify .qc code with Toffolis it should work out of the box. If you're doing something with the internals of Feynman's verification tools, the Toffoli path sum is given here: https://github.com/meamy/feynman/blob/master/src/Feynman/Algebra/Pathsum/Balanced.hs#L375.

2. The Z with three inputs is the CCZ gate. Zd is a hint to the compiler to use the dagger of the CCZ implementation. In general, in .qc you can add controls to any gate by giving more inputs, so for example `Z x` is a `Z` gate on qubit `x`, while `Z x y` is a controlled-Z gate with control `x` and target `y`. Likewise, `H x y z` would be a Hadamard gate controlled on `x` and `y` with target `z`

The closest thing to a formal spec would be in the (very old now) documentation for QCViewer (https://github.com/aparent/QCViewer/tree/master/docs). And yes, it should fully meet the spec of Symbolic.hs.

**Comment by alan23273850** [comment]
Hello, thank you for your very fast and detailed response! However, [grover8.txt](https://github.com/meamy/feynman/files/9753632/grover8.txt) still does not pass the command `./feynver grover8.qc grover8.qc`. The output message instead says:
```
feynver: Uninterpreted gates not supported
CallStack (from HasCallStack):
  error, called at src/Feynman/Verification/Symbolic.hs:49:20 in Feynman-0.1.0.0-64NHgio1wa2CbkU59446r5:Feynman.Verification.Symbolic
```

So how to modify the circuit file to allow the use of "Toffoli" gates? Thanks again!

**Comment by alan23273850** [comment]
Sorry for misidentifying the problem previously! Later, I've found that my problem occurs at Z gates (corresponding to the 2nd item mentioned above).

For example, the following .qc file allows the command `./feynver test.qc test.qc` to be executed.
```
.v q0 q1 q2

BEGIN
Z q0
END
```
and
```
.v q0 q1 q2

BEGIN
Z q0 q1 q2
END
```
also does, but
```
.v q0 q1 q2

BEGIN
Z q0 q1
END
```
the so-called CZ gate does not work!

More interestingly, the repo-provided benchmark file https://github.com/meamy/feynman/blob/master/benchmarks/shor_2_21.qc
does not allow the command `./feynver benchmarks/shor_2_21.qc benchmarks/shor_2_21.qc` either.

So, is there any way to allow the use of CNOT gates? Thanks again!

**Comment by alan23273850** [comment]
My circuit now works fine! Thanks for your instant fix!
